{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zic.builders_zenith",
    "module": "Builders-Zenith",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Builders-Zenith-0.1.5.jar",
          "url": "Builders-Zenith-0.1.5.jar",
          "size": 4356314,
          "sha512": "b2d867b87fda1f9552500725a6d28cdfb22175da19f832cca87a8367fc4f98325eba849d8dbe10a784161d3028dc5cb58c59157a6f74b4c734f7a9b44278f8de",
          "sha256": "1360647c962080596ce1e9a6469f955e41201d4753e731b55a15a25f1ca8f39a",
          "sha1": "ecb1387c043830a5593e678ecfc2ac4a68abdb86",
          "md5": "8b8ba0276957571355c53913095bc7ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "Builders-Zenith-0.1.5.jar",
          "url": "Builders-Zenith-0.1.5.jar",
          "size": 4356314,
          "sha512": "b2d867b87fda1f9552500725a6d28cdfb22175da19f832cca87a8367fc4f98325eba849d8dbe10a784161d3028dc5cb58c59157a6f74b4c734f7a9b44278f8de",
          "sha256": "1360647c962080596ce1e9a6469f955e41201d4753e731b55a15a25f1ca8f39a",
          "sha1": "ecb1387c043830a5593e678ecfc2ac4a68abdb86",
          "md5": "8b8ba0276957571355c53913095bc7ce"
        }
      ]
    }
  ]
}
